#!/bin/sh

# Wi-Fi
WIFI_SSID="CHANGE_ME"
WIFI_SECURITY="WPA"
WIFI_PASSWORD="CHANGE_ME"

# Image and time
TIMEZONE="Europe/Kyiv"
LED_INDICATOR="off"
FULL_COLOR="off"
NIGHT_VISION="auto"
WDR="on"
WATERMARK="on"
VIDEO_FLIP="off"
VIDEO_FPS="25"

# Stable media profile
MEDIA_ENABLE="on"
BACKCHANNEL_ENABLE="on"
PTZ_ENABLE="off"
AUDIO_START_DELAY="120"
BACKCHANNEL_START_DELAY="20"
BACKCHANNEL_RESTART_DELAY="10"

# ONVIF and web authentication
ONVIF_PORT="5000"
ONVIF_USERNAME="admin"
ONVIF_PASSWORD="CHANGE_ME"
ONVIF_MANUFACTURER="Xiaomi"
ONVIF_MODEL="MJSXJ05CM"

WEB_PORT="80"
WEB_AUTH="on"
WEB_USERNAME="${ONVIF_USERNAME}"
WEB_PASSWORD="${ONVIF_PASSWORD}"

# FTP is intended only for a trusted LAN.
FTP_ENABLE="on"
FTP_PORT="2121"
FTP_ROOT="/mnt/sdcard"
